package ${basePackage}.dao;

import ${baseDAOPackage};
import ${basePackage}.entity.${entityName};


/**
 *
 * 
 * Generated by fieldmeta at ${nowTime}
 *
 */

public interface ${entityName}DAO extends BaseRepository<${entityName}, Long> {

}
