package ${basePackage}.service;

import ${baseServicePackage};
import ${basePackage}.entity.${entityName};



/**
 *
 * 
 * Generated by fieldmeta at ${nowTime}
 *
 */
 
public interface ${entityName}Service extends BaseService<${entityName}, Long>{

}
