package ${basePackage}.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


import ${baseServiceImplPackage};
import ${basePackage}.dao.${entityName}DAO;
import ${basePackage}.entity.${entityName};



/**
 *
 * 
 * Generated by fieldmeta at ${nowTime}
 *
 */
 
@Service
public class ${entityName}ServiceImpl  extends BaseServiceImpl<${entityName}, Long> implements ${entityName}Service{
	@Autowired
	${entityName}DAO ${entityName_first_lowcase}DAO;
}
