## 网站配置
logo: 
  ## 网站名称
  title: "springboot-v2"
  ## 网站图标
  image: "../static/admin/images/logo.png"
## 菜单配置
menu: 
  ## 菜单数据来源
  data: /admin/getUserMenu
  ## 是否同时只打开一个菜单目录
  accordion: true
  ## 是否开启多系统菜单模式
  control: false
  ## 默认选中的菜单项
  select: "10"
  ## 是否开启异步菜单，false 时 data 属性设置为菜单数据，false 时为 json 文件或后端接口
  async: true
## 视图内容配置
tab: 
  ## 是否开启多选项卡
  muiltTab: true
  ## 切换选项卡时，是否保持页面状态
  keepState: true
  ## 最大可打开的选项卡数量
  tabMax: 30
  ## Tab 记忆
  session: true
  ## 默认选项卡数据
  index: 
    id: "10" ## 标识 ID , 建议与菜单项中的 ID 一致
    href: "/ServiceController/view" ## 页面地址
    title: "首页" ## 标题
## 主题配置
theme: 
  ## 默认主题色，对应 colors 配置中的 ID 标识
  defaultColor: "2"
  ## 默认的菜单主题 dark-theme 黑 / light-theme 白
  defaultMenu: "dark-theme"
  ## 是否允许用户切换主题，false 时关闭自定义主题面板
  allowCustom: true
## 供选择的主题色配置列表
colors: 
- id: "1"
  color: "#2d8cf0"
- id: "2"
  color: "#36b368"
- id: "3"
  color: "#f6ad55"
- id: "4"
  color: "#f56c6c"
- id: "5"
  color: "darkgray"
## 主题面板的链接列表配置
links: 
- icon: "layui-icon layui-icon-website"
  title: "官方网站"
  href: "http://www.pearadmin.com"
- icon: "layui-icon layui-icon-read"
  title: "开发文档"
  href: "http://www.pearadmin.com/doc/"
- icon: "layui-icon layui-icon-fonts-code"
  title: "开源地址"
  href: "https://gitee.com/pear-admin/Pear-Admin-Layui"
- icon: "layui-icon layui-icon-survey"
  title: "问答社区"
  href: "http://forum.pearadmin.com/"
## 其他配置
other: 
  ## 主页动画时长
  keepLoad: "1200"
  ## 布局顶部主题
  autoHead: false
header:
  ## 站内消息，数据来源，通过 false 设置关闭
  message: false ##"system/notice/notice"