package org.coderfun.fieldmeta.dao;

import org.coderfun.fieldmeta.entity.TemplateFile;

import klg.j2ee.common.dataaccess.BaseRepository;


/**
 *
 * 
 * Generated by fieldmeta at 2019-08-10T13:41:41+08:00
 *
 */

public interface TemplateFileDAO extends BaseRepository<TemplateFile, Long> {

}
