package com.jun.plugin.fieldmeta.dao;

import com.jun.plugin.common.dataaccess.BaseRepository;
import com.jun.plugin.fieldmeta.entity.TemplateFile;


/**
 *
 * 
 * Generated by fieldmeta at 2019-08-10T13:41:41+08:00
 *
 */

public interface TemplateFileDAO extends BaseRepository<TemplateFile, Long> {

}
