<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ruoyi-modules</artifactId>
        <groupId>com.ruoyi</groupId>
        <version>3.9.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ruoyi-modules-starter</artifactId>
    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-module-form</artifactId>
        </dependency>
        <!-- TODO: tenant依赖LoginUser扩展，待SB2升级后启用 -->
        <!-- <dependency><groupId>com.ruoyi</groupId><artifactId>ruoyi-module-tenant</artifactId></dependency> -->
        <!-- TODO: flowable待适配 -->
        <!-- <dependency><groupId>com.ruoyi</groupId><artifactId>ruoyi-module-flowable</artifactId></dependency> -->
        <!-- TODO: 适配后启用
        <dependency><groupId>com.ruoyi</groupId><artifactId>ruoyi-module-message</artifactId></dependency>
        <dependency><groupId>com.ruoyi</groupId><artifactId>ruoyi-module-online</artifactId></dependency>
        <dependency><groupId>com.ruoyi</groupId><artifactId>ruoyi-module-datarule</artifactId></dependency>
        <dependency><groupId>com.ruoyi</groupId><artifactId>ruoyi-module-oss</artifactId></dependency>
        -->
    </dependencies>
</project>
