Vagrant.configure("2") do |config|
  config.vm.box = "centos7"
  config.vm.define "master" do |master|
  	master.vm.network "private_network", ip: "192.168.33.11"
  	master.vm.hostname = "master"
  	master.vm.provider "virtualbox" do |v|
	  v.memory = 2048
	  v.cpus = 2
	end
  end

  config.vm.define "node1" do |node1|
  	node1.vm.network "private_network", ip: "192.168.33.12"
  	node1.vm.hostname = "node1"
  	node1.vm.provider "virtualbox" do |v|
	  v.memory = 5120
	  v.cpus = 2
	end
  end

  config.vm.define "node2" do |node2|
  	node2.vm.network "private_network", ip: "192.168.33.13"
  	node2.vm.hostname = "node2"
  	node2.vm.provider "virtualbox" do |v|
	  v.memory = 5120
	  v.cpus = 2
	end
  end
  config.vm.define "node3" do |node3|
  	node3.vm.network "private_network", ip: "192.168.33.14"
  	node3.vm.hostname = "node3"
  	node3.vm.provider "virtualbox" do |v|
	  v.memory = 5120
	  v.cpus = 2
	end
  end
  config.vm.define "nfs" do |nfs|
  	nfs.vm.network "private_network", ip: "192.168.33.15"
  	nfs.vm.hostname = "nfs"
  	nfs.vm.provider "virtualbox" do |v|
	  v.memory = 1024
	  v.cpus = 1
	end
  end
  config.vm.define "extend" do |extend|
  	extend.vm.network "private_network", ip: "192.168.33.16"
  	extend.vm.hostname = "extend"
  	extend.vm.provider "virtualbox" do |v|
	  v.memory = 7168
	  v.cpus = 2
	end
  end
end