<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>ruoyi-plugins</artifactId>
        <groupId>com.ruoyi</groupId>
        <version>3.9.2</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
	<artifactId>ruoyi-plugin-alioss</artifactId>
	<description>
		阿里云OSS对象存储
	</description>

	<dependencies>

		<dependency>
			<groupId>com.ruoyi</groupId>
			<artifactId>ruoyi-common</artifactId>
		</dependency>


		<!--阿里云oss-->
		<dependency>
			<groupId>com.aliyun.oss</groupId>
			<artifactId>aliyun-sdk-oss</artifactId>
			<version>3.18.1</version>
		</dependency>
	        <dependency><groupId>org.projectlombok</groupId><artifactId>lombok</artifactId><optional>true</optional></dependency>
    </dependencies>
</project>
