version: '2' # 表示该 Docker-Compose 文件使用的是 Version 2 file
services:
  boot-mongo-admin:  # 指定服务名称
    build: ./java/  # 指定 Dockerfile 所在路径
    # image: shuogesha/boot-mongo-admin
    ports:    # 指定端口映射
      - "8080:8080"
    links:
      - mymongo
  boot-mongo-admin-nginx:  # 指定服务名称
    build: ./vue-admin/  # 指定 Dockerfile 所在路径
    # image: shuogesha/boot-mongo-admin-nginx
    ports:    # 指定端口映射
      - "18080:80" 
    links:
      - boot-mongo-admin
  mymongo:
    image: mongo:4.0
    ports:    # 指定端口映射
      - "27017:27017"
    volumes:
      - ./data:/data/db
    privileged: true