apiVersion: v1
kind: ReplicationController
metadata:
  name: nacos-mysql-slave
  labels:
    name: nacos-mysql-slave
spec:
  replicas: 1
  selector:
    name: nacos-mysql-slave
  template:
    metadata:
      labels:
        name: nacos-mysql-slave
    spec:
      containers:
        - name: slave
          image: nacos/nacos-mysql-slave:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: nacos-mysql-slave-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-cm
                  key: nacos.mysql.slave.root.password
            - name: MYSQL_REPLICATION_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-cm
                  key: nacos.mysql.replication.user
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-cm
                  key: nacos.mysql.replication.password
      volumes:
        - name: nacos-mysql-slave-data
          nfs:
            path: /nfs/nacos-mysql-slave
            server: 192.168.33.15
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave # 必须叫这个名字，因为nacos server内部根据这个名字连接数据库
  labels:
    name: mysql-slave
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: nacos-mysql-slave