var appId = document.getElementById('kefuScript').getAttribute('appid');
var robot = document.getElementById('kefuScript').getAttribute('robot');
/** 客服css样式 */document.writeln("<link rel='stylesheet' href='kefu.css'/*tpa=https://ics.chinasoftinc.com/pptemplate/default/theme/default/kefu/kefu.css*//>");
///** 客服jquery */document.writeln("<script type='text/javascript' src='jquery.js'/*tpa=http://ics.chinasoftosg.com/pptemplate/default/theme/default/kefu/jquery.js*/></script>");
/** robot css样式 */document.writeln("<link rel='stylesheet' type='text/css' href='index.css'/*tpa=https://ics.chinasoftinc.com:31004/index.css*/ />");
/** robot css样式 */document.writeln("<script type='text/javascript' src='https://ics.chinasoftinc.com:31004/getUser.js'></script>");
/** robot css样式 */document.writeln("<script type='text/javascript' src='https://ics.chinasoftinc.com:31004/index.js'></script>");
/** 客服设置cookie */document.writeln("<script type='text/javascript' src='https://ics.chinasoftinc.com/pptemplate/default/spage/ItSelfService/js/jquery.cookie.js'></script>");
/** 客服弹窗脚本 */document.writeln("<script type='text/javascript' src='https://ics.chinasoftinc.com/pptemplate/default/theme/default/kefu/popwin.js?v=3'></script>");
///** 客服设置cookie */document.writeln("<script type='text/javascript' src='js.cookie.js'/*tpa=http://ics.chinasoftosg.com/pptemplate/default/theme/default/kefu/js.cookie.js*/></script>");

/** 客户悬浮窗 */if('true'==robot){document.writeln("<div class='kefu hidden-xs'><div><a onclick=\" openChatVersion();\" class='kefu-lx' title='中软国际小助' target='_blank'>中软国际小助</a></div> <ul class='list-unstyled'><li><a  onclick=\" openChatVersion();\" title='中软国际小助' target='_blank' class='kf' rel='nofollow' style='color:#fff;'>中软国际小助</a></li><li><a  onclick=\" openChatVersion();\" title='中软国际小助' target='_blank' class='kefu-zx' rel='nofollow' style='color:#fff;'>中软国际小助</a></li> <li><a href='jk_IT.html'/*tpa=https://ics.chinasoftinc.com/pptemplate/default/spage/jk_IT.html*/ target='_blank' class='kefu-yy' title='IT联系电话' rel='nofollow' style='color:#fff;'>IT联系电话</a></li> </ul></div> ")};
///** 客户悬浮窗 */document.writeln("<div class='kefu hidden-xs'><div><a onclick=\"Mibew.Objects.ChatPopups['596ec358efa651a8'].open();return false;\" href='http://117.78.32.136/mibew/index.php/chat?locale=zh-cn&style=default&group=1' class='kefu-lx' title='联系我们' target='_blank'>联系我们</a></div> <ul class='list-unstyled'> <li><a style='color:#fff;' href='http://117.78.32.136/mibew/index.php/chat?locale=zh-cn&style=default&group=1' onclick=\"Mibew.Objects.ChatPopups['596ec358efa651a8'].open();return false;\" target='_blank' class='kf' rel='nofollow'>IT问题<br>在线支持</a></li> <li><a href='http://117.78.32.136/mibew/index.php/chat?locale=zh-cn&style=default&group=1' onclick=\"Mibew.Objects.ChatPopups['596ec358efa651a8'].open();return false;\" title='网页在线咨询' target='_blank' class='kefu-zx' rel='nofollow' style='color:#fff;'>在线咨询</a></li><li><a href='http://ics.chinasoftosg.com/pptemplate/default/page/jk_IT.html' target='_blank' class='kefu-yy' title='联系电话' rel='nofollow' style='color:#fff;'>029-89633963</a></li> <li><a href='http://ics.chinasoftosg.com/pptemplate/default/page/ItSelfService/index.html' target='_blank' class='kefu-qq' title='IT自助服务平台' rel='nofollow' style='color:#fff;'>IT自助服务</a></li><li><a href='#' class='kefu-top' title='回网页顶部' rel='nofollow'></a></li><li><a href='#' class='kefu-di' title='回网页底部' rel='nofollow'></a></li> </ul></div> ");
///** 在线客服图标 */document.writeln("<a id='mibew-agent-button' href='http://117.78.32.136/mibew/index.php/chat?locale=zh-cn&style=default&group=1' target='_blank' onclick=\"Mibew.Objects.ChatPopups['596ec358efa651a8'].open();return false;\" ><img src='http://117.78.32.136/mibew/index.php/b?i=mibew&lang=zh-cn&group=1' border='0' alt='' /></a><script type='text/javascript' src='chat_popup.js'/*tpa=http://117.78.32.136/mibew/js/compiled/chat_popup.js*/></script><script type='text/javascript'>Mibew.ChatPopup.init({'id':'596ec358efa651a8','url':'http:\/\/117.78.32.136\/mibew\/index.php\/chat?locale=zh-cn&style=default&group=1','preferIFrame':true,'modSecurity':false,'height':480,'width':640,'resizable':true,'styleLoader':'http:\/\/117.78.32.136\/mibew\/index.php\/chat\/style\/popup\/default'});</script>");
///** 在线客服图标 */document.writeln("<a id='mibew-agent-button' href='http://117.78.32.136/mibew/index.php/chat?locale=zh-cn&style=default&group=1' target='_blank' onclick=\"Mibew.Objects.ChatPopups['596ec358efa651a8'].open();return false;\" ><img src='http://117.78.32.136/mibew/index.php/b?i=mibew&lang=zh-cn&group=1' border='0' alt='' /></a><script type='text/javascript' src='chat_popup.js'/*tpa=http://117.78.32.136/mibew/js/compiled/chat_popup.js*/></script><script type='text/javascript'>Mibew.ChatPopup.init({'id':'596ec358efa651a8','url':'http:\/\/117.78.32.136\/mibew\/index.php\/chat?locale=zh-cn&style=default&group=1','preferIFrame':true,'modSecurity':false,'height':480,'width':640,'resizable':true,'styleLoader':'http:\/\/117.78.32.136\/mibew\/index.php\/chat\/style\/popup\/default'});</script>");
///** 应用底部弹出窗口 */document.writeln("<script>var popflag=true; $.get('http://ics.chinasoftosg.com:8000/popnotify/',  { appname: 'test' },  function(data){   var dataObj = eval(\"(\"+data+\")\");  popflag = Boolean(dataObj.flag);  if(!popflag){  $(\"#popPage\").hide() ;  }  }  ).error(function(xhr,errorText,errorType){ $(\"#popPage\").show() ;  });   (function(){    function getFloatPage(){  var url='http://ics.chinasoftosg.com:8000/popnotify/?appname=test',  height=302,  frame = document.createElement('iframe'),  popPage = document.createElement('div'),  oWndTop = document.createElement('div'),oWndDown = document.createElement('div')，  oWndClose = document.createElement('span'), oWndOK = document.createElement('span');  popPage.style.cssText='width:304px;height:308px;left:50%;top:50%;margin-left:-150px;margin-top:-150px;line-height:220px;z-index: 100;position: fixed;*zoom:0;*z-index:100;_top:expression(eval(document.documentElement.scrollTop));';  popPage.setAttribute('id','popPage');  frame.setAttribute('src', url);   frame.setAttribute('height', height);  frame.setAttribute('frameborder','no');  frame.setAttribute('border','0');  oWndTop.setAttribute('id','divWndTop');  oWndTop.style.cssText = 'height:24px ;width:280px;float:right;overflow:hidden;position: fixed;';oWndDown.setAttribute('id','divWndDown');  oWndDown.style.cssText = 'height:24px ;width:280px;float:bottom;overflow:hidden;position: fixed;';  popPage.appendChild(oWndTop);popPage.appendChild(oWndDown);  oWndClose.setAttribute('id','spanWndClose');  oWndClose.setAttribute('title','关闭');  $(oWndTop).addClass('wndClose');   oWndTop.appendChild(oWndClose);   oWndDown.appendChild(oWndClose);  popPage.appendChild(frame);  document.body.appendChild(popPage);  closeWin();  }  return getFloatPage();   })();  $('#spanWndClose').click(function(){  try{window.top.glbWndObj.funcBeforeClose();}catch(e){}  closeWin();  });  function closeWin(){  $('#popPage').hide() ; }</script>");
///** 应用中部弹出窗口 */document.writeln("<script>var popflag=true;var notshowflag=Cookies.get('notShow', { domain: 'https://ics.chinasoftinc.com/pptemplate/default/theme/default/kefu/ics.chinasoftosg.com' });console.log(notshowflag); $.get('http://ics.chinasoftosg.com:8000/popnotify/',  { appname: '"+appId+"' },  function(data){   var dataObj = eval(\"(\"+data+\")\");  popflag = Boolean(dataObj.flag);  if(!popflag){  $(\"#popPage\").hide() ;Cookies.set('notShow', 'false',{ domain: 'https://ics.chinasoftinc.com/pptemplate/default/theme/default/kefu/ics.chinasoftosg.com' });  }  }  ).error(function(xhr,errorText,errorType){if('true' != notshowflag) { popWin.showWin('600','300','','http://ics.chinasoftosg.com:8000/popnotify/?appname="+appId+"')} ;  });</script>"); 
///** 应用中部弹出窗口 */document.writeln("<script>var popflag = 0;var notifylable='';var readflag = 1;var notshowflag=$.cookie('notShow'); $.get('http://ics.chinasoftosg.com:8000/popnotify/',  { appname: '"+appId+"' },  function(data){   var dataObj = eval(\"(\"+data+\")\");  popflag = parseInt(dataObj.flag);notifylable = dataObj.notifylable;console.log(notifylable);$.get('http://ics.chinasoftosg.com:8088/notify.aspx',  {notifylable:notifylable,readflag:'-1', appname: '"+appId+"' },  function(data){   var dataObj = eval(\"(\"+data+\")\");readflag = parseInt(dataObj.readflag);console.log('222'+readflag);}).error(function(xhr,errorText,errorType){ console.log('1111'+errorText);});  if(popflag>=0 & readflag<=0){ if('true' != notshowflag) { popWin.showWin('600','300',popflag,'http://ics.chinasoftosg.com:8000/popnotifyc/?appname="+appId+"')} } else {  $(\"#popPage\").hide() ;$.cookie('notShow','false');}  }  ).error(function(xhr,errorText,errorType){ console.log(errorText);});</script>"); 

