spring:
  # datasource
  datasource:
    url: jdbc:mysql://s1.iocoder.cn:3306/mall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 3WLiVUBEwTbvAfsh

  # Spring Cloud 配置项
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: s1.iocoder.cn:8848 # Nacos 服务器地址

    # Spring Cloud Stream 配置
    stream:
      # Binding 配置项
      bindings:
        product-update-output:
          destination: ProductUpdate
      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Binder 配置项
        binder:
          name-server: s1.iocoder.cn:9876 # RocketMQ Namesrv 地址
        # RocketMQ 默认 Binding 配置项
        default:
          # RocketMQ 生产者
          producer:
            group: product-producer-group # 生产者分组
            sync: true # 是否同步发送消息，默认为 false 异步。

# mybatis
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.iocoder.mall.product.dataobject

# Dubbo 配置项
dubbo:
  # Dubbo 注册中心
  registry:
    address: spring-cloud://s1.iocoder.cn:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置
  cloud:
    subscribed-services: admin-application, user-application # 设置订阅的应用列表，默认为 * 订阅所有应用
  # Dubbo 提供者的协议
  protocol:
    name: dubbo
    port: -1
  # Dubbo 提供服务的扫描基础包
  scan:
    base-packages: cn.iocoder.mall.product.service
  # Dubbo 服务提供者的配置
  provider:
    filter: -exception
    ProductAttrService:
      version: 1.0.0
    ProductCategoryService:
      version: 1.0.0
    ProductSpuService:
      version: 1.0.0
    ProductBrandService:
      version: 1.0.0
    OAuth2Service:
      version: 1.0.0
    ProductSpuCollectionService:
      version: 1.0.0
    UserProductSpuCollectionsService:
      version: 1.0.0
  consumer:
    UserService:
      version: 1.0.0

# Seata 配置项
seata:
  tx-service-group: default # Seata 事务组编号，用于 TC 集群名
  # 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      default: default
  # Seata 注册中心配置项
  registry:
    type: nacos # 注册中心类型
    nacos:
      serverAddr: ${spring.cloud.nacos.discovery.server-addr} # Nacos 服务地址
      namespace: # Nacos 命名空间
      cluster: default # 使用的 Seata 分组

