# \u6CE8\u610F\uFF1A\u540C\u7EA7\u76EE\u5F55\u4E0B\uFF0Capplication.properties \u52A0\u8F7D\u4F18\u5148\u7EA7\u9AD8\u4E8Eapplication.yml\uFF0C\u4F1A\u8986\u76D6 application.yml\uFF0C\u6240\u4EE5\u53EA\u80FD\u4FDD\u7559\u5176\u4E2D\u4E00\u79CD\u7C7B\u578B

# \u5E94\u7528\u540D\u79F0
spring.application.name=ruoyi.mq

# RabbitMQ\u914D\u7F6E
#spring.rabbitmq.enabled=true
spring.rabbitmq.virtual-host=/
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
# \u786E\u8BA4\u673A\u5236
spring.rabbitmq.publisher-confirms=true
# \u6D88\u606F\u662F\u5426\u8981\u786E\u8BA4
spring.rabbitmq.publisher-returns=true
# \u786E\u8BA4\u673A\u5236\u6A21\u5F0F
spring.rabbitmq.listener.simple.acknowledge-mode=manual
# \u5E76\u53D1\u6570
spring.rabbitmq.listener.simple.concurrency=1
# \u6700\u5927\u5E76\u53D1\u6570
spring.rabbitmq.listener.simple.max-concurrency=5
# \u9884\u66F4\u65B0\u6B21\u6570
spring.rabbitmq.listener.simple.prefetch=5
# \u6279\u91CF\u63D0\u4EA4\u5927\u5C0F
spring.rabbitmq.listener.simple.transaction-size=5
spring.rabbitmq.listener.simple.retry.enabled=true
# \u6700\u5927\u91CD\u8BD5\u6B21\u6570
spring.rabbitmq.listener.simple.retry.max-attempts=5
# \u521D\u59CB\u91CD\u8BD5\u65F6\u95F4
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.default-requeue-rejected=false
# \u5FC3\u8DF3
spring.rabbitmq.requested-heartbeat=0
# \u81EA\u5B9A\u4E49\u961F\u5217\u548Crouter\uFF0C# key\uFF1A\u961F\u5217\u540D\u79F0\uFF0C value: \u8DEF\u7531
# spring.rabbitmq.queue.flow-queue=flow-router
# \u961F\u5217\u540D\u79F0
# spring.rabbitmq.queueName=flow-queue
