import app from '@/app'
import { isProduction } from '@/utils/utils.ts'

import {
  ConfigProvider,
  Layout,
  Input,
  InputNumber,
  Button,
  Switch,
  Radio,
  Checkbox,
  Select,
  Card,
  Form,
  Row,
  Col,
  Modal,
  Table,
  Tree,
  Tabs,
  Badge,
  Popover,
  Dropdown,
  List,
  Avatar,
  Breadcrumb,
  Steps,
  Spin,
  Menu,
  Drawer,
  Tooltip,
  Alert,
  Tag,
  Divider,
  DatePicker,
  TimePicker,
  Upload,
  Progress,
  Skeleton,
  Popconfirm,
  PageHeader,
  Result,
  Statistic,
  Descriptions,
  Space
} from 'ant-design-vue'

app.use(ConfigProvider)
app.use(Layout)
app.use(Input)
app.use(InputNumber)
app.use(Button)
app.use(Switch)
app.use(Radio)
app.use(Checkbox)
app.use(Select)
app.use(Card)
app.use(Form)
app.use(Row)
app.use(Col)
app.use(Modal)
app.use(Table)
app.use(Tree)
app.use(Tabs)
app.use(Badge)
app.use(Popover)
app.use(Dropdown)
app.use(List)
app.use(Avatar)
app.use(Breadcrumb)
app.use(Steps)
app.use(Spin)
app.use(Menu)
app.use(Drawer)
app.use(Tooltip)
app.use(Alert)
app.use(Tag)
app.use(Divider)
app.use(DatePicker)
app.use(TimePicker)
app.use(Upload)
app.use(Progress)
app.use(Skeleton)
app.use(Popconfirm)
app.use(PageHeader)
app.use(Result)
app.use(Statistic)
app.use(Descriptions)
app.use(Space)

!isProduction && console.info('%cPear Info: 已按需加载ant-design-vue组件!', 'background: #36b368; color: white;font-size: 15px;')
