# 服务器的配置项
server:
  port: 18083
  servlet:
    context-path: /management-api/

spring:
  # Application 的配置项
  application:
    name: management-web
  # Profile 的配置项
  profiles:
    active: local
  # SpringMVC 配置项
  mvc:
    throw-exception-if-no-handler-found: true # 匹配不到路径时，抛出 NoHandlerFoundException 异常
    static-path-pattern: /doc.html # 静态资源的路径

# Dubbo 配置项
dubbo:
  # Spring Cloud Alibaba Dubbo 专属配置
  cloud:
    subscribed-services: 'system-service' # 设置订阅的应用列表，默认为 * 订阅所有应用
  # Dubbo 服务消费者的配置
  consumer:
    timeout: 10000
    validation: true # 开启 Consumer 参数校验
    check: false # 本地启动，不进行校验，不一定会使用到未启动的服务，嘿嘿~
    UserSmsCodeRpc:
      version: 1.0.0
    UserRpc:
      version: 1.0.0
    OAuth2Rpc:
      version: 1.0.0
    AdminRpc:
      version: 1.0.0
    ResourceRpc:
      version: 1.0.0
    RoleRpc:
      version: 1.0.0
    PermissionRpc:
      version: 1.0.0
    DepartmentRpc:
      version: 1.0.0
    DataDictRpc:
      version: 1.0.0
    SystemAccessLogRpc:
      version: 1.0.0
    SystemExceptionLogRpc:
      version: 1.0.0
    ErrorCodeRpc:
      version: 1.0.0
    ProductCategoryRpc:
      version: 1.0.0
    ProductBrandRpc:
      version: 1.0.0
    ProductSpuRpc:
      version: 1.0.0
    ProductAttrRpc:
      version: 1.0.0
    CouponTemplateRpc:
      version: 1.0.0
    PromotionActivityRpc:
      version: 1.0.0
    BannerRpc:
      version: 1.0.0
    ProductRecommendRpc:
      version: 1.0.0
    PayTransactionRpc:
      version: 1.0.0

# Swagger 配置项
swagger:
  title: 管理后台
  description: 提供管理员管理的所有功能
  version: 1.0.0
  base-package: cn.iocoder.mall.managementweb.controller

# Actuator 监控配置项
management:
  server.port: 38087 # 独立端口，避免被暴露出去
  endpoints.web.exposure.include: '*' # 暴露所有监控端点
