apiVersion: v1
kind: ConfigMap
metadata:
  name: febs-cm
data:
  febs.mysql.url: "febs-mysql-service" # 对应K8S集群外部MySQL服务Service
  febs.redis.url: "febs-redis-service" # 对应K8S集群外部Redis服务Service
  febs.auth.url: "febs-auth-service" # 对应K8S集群内部febs-auth服务Service
  nacos.url: "nacos-service" # 对应K8S集群内部nacos服务Service
  febs.monitor.admin.url: "febs-monitor-admin-service" # 对应K8S集群外部febs-monitor-admin服务Service
  febs.gateway.url: "febs-gateway-service" # 对应K8S集群内部febs-gateway服务Service
  logstash.url: "logstash-service" # 对应K8S集群外部logstash服务Service