server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
    basedir: /tmp/  
spring:   
  application:
      name: questions-java
#  main:
#    allow-bean-definition-overriding: true 
  aop:
    proxy-target-class: true
    auto: true 
  resources:
    staticLocations: classpath:/templates/,classpath:/static/page 
    #默认单个数据源的配置
  data:
    mongodb:
#    uri: mongodb://root:root@127.0.0.1:27017/boot-mongo-admin
      uri: mongodb://127.0.0.1:27017/boot-mongo-admin
   # Quartz 的配置，对应 QuartzProperties 配置类
  quartz:
    job-store-type: jdbc # Job 存储器类型。默认为 memory 表示内存，可选 jdbc 使用数据库。
    auto-startup: true # Quartz 是否自动启动
    startup-delay: 0 # 延迟 N 秒启动
    wait-for-jobs-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
    overwrite-existing-jobs: true # 是否覆盖已有 Job 的配置
    properties: # 添加 Quartz Scheduler 附加属性
      org:
        quartz:
          threadPool:
            threadCount: 25 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 线程池类型
          scheduler:
            instancName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: com.novemberain.quartz.mongodb.MongoDBJobStore
#            mongoUri: mongodb://用户名:密码@10.10.17.8:27017,10.10.17.9:27017,10.10.17.10:27017/数据库
            mongoUri: mongodb://127.0.0.1:27017/boot-mongo-admin
            collectionPrefix: quartz
            isClustered: true
            clusterCheckinInterval: 10000
            triggerTimeoutMillis: 1200000
            misfireThreshold: 1800000
            jobDataAsBase64: false
#            addresses: host1,host2
      
 ##图片临时路径
#文件上传目录(window是d/e/f盘， linux是/)（注意Linux和Windows上的目录结构不同）
file:
  uploadFolder: /Users/zhaohaiyuan/Downloads/upload/
#静态资源对外暴露的访问路径(访问图片的路径)
  staticAccessPath: /upload/**  
#打印SQL日志 
logging:
 #path: ./logs/ #打印存放日志的路径
 level:
  com.shuogesha: DEBUG #包名下日志的级别
#swagger
swagger:
  enable: true
  info:
    version: 0.1
    title: BMA接口
    description: BMA后台管理系统