/* Generated by Together */

package org.myframework.support.idgenerator.util;

import org.myframework.commons.GeneralRuntimeException;

/**
 * <p>
 * Title: 稽查异常,非检查，支持嵌套
 * </p>
 * <p>
 * Description: 航信税务软件-稽查部分
 * </p>
 * <p>
 * Copyright: Copyright (c) 2004
 * </p>
 * <p>
 * Company: 合力金桥软件公司
 * </p>
 * 
 * @author Wujun
 * @version 1.0
 */
public class IDGeneratorException extends GeneralRuntimeException {
	public IDGeneratorException(String msg, Throwable ex) {
		super(msg, ex);
	}

	public IDGeneratorException(String msg) {
		super(msg);
	}

	public IDGeneratorException(String msg, String errorCode) {
		super(msg);
		this.errorCode = errorCode;
	}

	public IDGeneratorException(String msg, String errorCode, Throwable ex) {
		super(msg, ex);
		this.errorCode = errorCode;
	}

	/**
	 * 返回错误代码
	 * 
	 * @return String
	 */
	public String getErrorCode() {
		return errorCode;
	}

	// 错误代码
	private String errorCode;
}
