<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>com.ruoyi</groupId><artifactId>ruoyi</artifactId><version>3.9.2</version><relativePath>../pom.xml</relativePath></parent>
    <artifactId>ruoyi-oa-biz</artifactId><version>1.0.0</version><packaging>pom</packaging><description>业务功能模块组</description>
    <modules><module>ruoyi-information</module><module>ruoyi-kbs</module><module>ruoyi-schedule</module><module>ruoyi-worksetting</module><module>ruoyi-serial</module><module>ruoyi-biz-sdk</module></modules>
</project>