spring:
  # 数据源配置项
  datasource:
    url: jdbc:mysql://400-infra.server.iocoder.cn:3306/mall_pay?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 3WLiVUBEwTbvAfsh
  # Spring Cloud 配置项
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: 400-infra.server.iocoder.cn:8848 # Nacos 服务器地址
        namespace: dev # Nacos 命名空间

# Dubbo 配置项
dubbo:
  # Dubbo 注册中心
  registry:
#    address: spring-cloud://400-infra.server.iocoder.cn:8848 # 指定 Dubbo 服务注册中心的地址
    address: nacos://400-infra.server.iocoder.cn:8848?namespace=dev # 指定 Dubbo 服务注册中心的地址
  # Dubbo 服务提供者的配置
  provider:
    tag: ${DUBBO_TAG} # Dubbo 路由分组

# XXL-Job 配置项
xxl:
  job:
    enabled: false # 本地开发时，关闭 XXL-Job
    admin:
      addresses: http://400-infra.server.iocoder.cn:9099
    executor:
      appname: ${spring.application.name}
    accessToken:


# MyBatis Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 本地开发环境下，多打印 SQL 到控制台
